# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    motd: "puppetlabs-motd"
    registry: "puppetlabs-registry"
    apache: "puppetlabs-apache"
    stdlib: "puppetlabs-stdlib"
    apt: "puppetlabs-apt"
    accounts: "puppetlabs-accounts"
    cron: "puppet-cron"
    sudo: "saz-sudo"
    sshkeys_core: "puppetlabs-sshkeys_core"
    powershell: "puppetlabs-powershell"
  repositories:
    profile: "https://x-access-token:${GITHUB_TOKEN}@github.com/murphycraig250/craig-profile.git"
